### ISSUE TITLE
brats results 

### ISSUE THREAD

**Issue by WSake** [BraTS/Instructions#12]
Dear author, Hello, I have recently encountered some problems with [https://ipp.cbica.upenn.edu/.](https://ipp.cbica.upenn.edu/) I have asked other users and found that they have the same problem. After uploading the results since 20 June, I have not received the results after a long time. I don't know what went wrong and look forward to your reply.

**Comment by christophbrgr** [comment]
Hi, sorry for the late reply! 

I am not involved with the Image Processing Portal and suggest you contact the support mail at the bottom of the page: https://ipp.cbica.upenn.edu
